Add new community drive model
gcivil-nyu-org/wed-fall24-team5 pull request #354
Opened 2024-11-24 22:47 UTC by maxgrove42

# #349

## Description

- Adds the community drive models into the database
- Establishes 3 tables:
  - CommunityDrive (for community drive management)
  - DriveVolunteer (for managing volunteers to community drives)
  - DriveOrganization (for managing participating organizations)

## Change Type (delete non-relevant options)

- 💡 New feature (non-breaking change which adds functionality)

2024-11-24 23:07 UTC, QahtanAlJammali commented on src/database/models.py
The DriveVolunteer I believe should have foreign key to auth_user id since each volunteer would have to be a user. 
I think first_name, last_name and email is found in auth_user. so technically we would only need a field called id which would be the Foreign key to the id in auth_user, and the name, email could be pulled from that.
meanwhile, phone_number is pulled from userprofile table.

2024-11-24 23:34 UTC, maxgrove42 commented on src/database/models.py
@QahtanAlJammali I def thought about that, but my only fear with that is what if an organization wants to commit volunteers that aren't members of our platform? I.e. I want to promise 5 employees from my organization but they don't want to make accounts from the platform.

2024-11-24 23:36 UTC, maxgrove42 commented on src/database/models.py
If we want to require volunteers to be members of the platform, that's fine then ! Let's discuss live Monday ?

2024-11-25 00:01 UTC, QahtanAlJammali commented on src/database/models.py
ah! I didn't think of that! I thought volunteers would sign up through the platform. 
If we require them to sign up, then we are adding a whole new persona, which is the person that signs up in the platform just for the sake of volunteering. 
Yep, lets discuss Monday! I am amenable to either flow. leaning a tad towards having the volunteers be users of the platform as well.

2024-11-25 00:20 UTC, estchang commented on src/database/models.py
Interesting problem! Right now we have a feature where if an organization owner tries to add an unregistered user as an admin, the system asks for confirmation and auto-creates a user in the database with the given email (+ temporary auto-generated password). What do you guys think about something like this? That way we could have the foreign key relationship, and the volunteer users created this way could choose whether or not to log in and use the platform.

2024-11-25 20:56 UTC, maxgrove42 commented
As discussed with team, removing DriveVolunteer table and having organizations commit just a # of volunteers.

2024-11-25 21:46 UTC, arsalananwar11 requested changes

2024-11-25 22:10 UTC, maxgrove42 commented on src/database/models.py
> +class DriveVolunteer(models.Model):
yea we aren't , i just haven't had time to change it since standup lol. see comment above !

2024-11-25 22:54 UTC, arsalananwar11 commented
> As discussed with team, removing DriveVolunteer table and having organizations commit just a # of volunteers.

Okay np, your comment said "removing DriveVolunteer table" but the file still had the table. So wanted to double check. Let us know once you remove/clean up the files!

2024-11-25 23:15 UTC, maxgrove42 commented
@arsalananwar11 updated!

2024-11-25 23:19 UTC, arsalananwar11 approved these changes
Thanks Max! Looks great!

2024-11-26 00:08 UTC, estchang commented
Looks awesome, thanks Max :)

2024-11-26 00:08 UTC, estchang approved these changes
Looks awesome, thanks Max :)

2024-11-26 01:02 UTC, merged